# Generated by Django 5.0.6 on 2024-05-27 22:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clientes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        choices=[
                            ("BAN", "Banho"),
                            ("TOS", "Tosa"),
                            ("ADE", "Adestramento Canino"),
                            ("HOS", "Hospedagem"),
                            ("VET", "Serviços Veterinários"),
                        ],
                        max_length=3,
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name="Services",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=30)),
                ("date_init", models.DateTimeField(null=True)),
                ("date_final", models.DateTimeField(null=True)),
                ("finished", models.BooleanField(default=False)),
                ("protocol", models.CharField(blank=True, max_length=32, null=True)),
                (
                    "client",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="clientes.cliente",
                    ),
                ),
                ("service_category", models.ManyToManyField(to="servicos.category")),
            ],
        ),
    ]
