# Generated by Django 5.0.6 on 2024-05-29 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("servicos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="services",
            name="identifier",
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
    ]
